DotnetMvc/WebMvc/Models/FoodViewModel.cs
namespace WebMvc.Models
{
    public class FoodViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public int Price { get; set; }

        public FoodViewModel() { }

        public FoodViewModel(int id, string name, string category, int price)
        {
            Id = id;
            Name = name;
            Category = category;
            Price = price;
        }
    }

    
}

DotnetMvc/WebMvc/Controllers/FoodController.cs
using Microsoft.AspNetCore.Mvc;
using WebMvc.Models;

namespace WebMvc.Controllers
{
    public class FoodController : Controller
    {

        public static List<FoodViewModel> foodList = new List<FoodViewModel>()
        {
            new FoodViewModel(1,"Soto Bogor", "Makanan", 10000),
            new FoodViewModel(2,"Iga Bakar", "Makanan", 25000),
            new FoodViewModel(3,"Mie Goreng Spesial", "Makanan", 15000),
            new FoodViewModel(4,"Pecel", "Makanan", 10000),
            new FoodViewModel(6,"Ayam Goreng Madura", "Makanan", 15000),
            new FoodViewModel(7,"Es Dawt", "Minuman", 10000),
            new FoodViewModel(8,"Jus Nangla", "Minuman", 10000),
            new FoodViewModel(9,"Es Campur", "Minuman", 15000),
            new FoodViewModel(10,"Air Putih Dingin", "Minuman", 5000)

        };

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {
            return View(foodList);
        }


        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Save([Bind("Id, Name, Category, Price")] FoodViewModel food)
        {
            foodList.Add(food);
            return Redirect("List");
        }
        public IActionResult Edit(int? id)
        {
            FoodViewModel food = foodList.Find(x => x.Id.Equals(id));
            return View(food);
        }
        [HttpPost]
        public IActionResult Update(int id, [Bind("Id, Name, Category, Price")] FoodViewModel food)
        {
            FoodViewModel foodOld = foodList.Find(x => x.Id.Equals(id));
            foodList.Remove(foodOld);
            foodList.Add(food);
            return View("List");
        }

        public IActionResult Detail(int id)
        {
            FoodViewModel food = (from c in foodList where c.Id.Equals(id) select c).SingleOrDefault(new FoodViewModel());

            return View(food);
        }
        public IActionResult Delete(int? id)
        {
            FoodViewModel food = foodList.Find(x => x.Id.Equals(id));
            foodList.Remove(food);

            return View("List");
        }



    }
}

DotnetMvc/WebMvc/Views/Food/Add.cshtml
@model FoodViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Menu";
}
<h2>Tambahkan Menu</h2>
<form asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="Id">Id</label>
        <input asp-for="Id" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Name">Nama</label>
        <input asp-for="Name" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Category"> Jenis </label>
        <input asp-for="Category" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Price">Harga</label>
        <input asp-for="Price" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DotnetMvc/WebMvc/Views/Food/Detail.cshtml
@model FoodViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Detail Menu";
}
<h2>Detail Menu</h2>
<table class="table tab-content">
    <tbody>
        <tr>
            <th>ID</th>
            <td>@Model.Id</td>
        </tr>
        <tr>
            <th>Nama Menu</th>
            <td>@Model.Name</td>
        </tr>

        <tr>
            <th>Jenis</th>
            <td>@Model.Category</td>
        </tr>
        <tr>
            <th>Harga</th>
            <td>@Model.Price</td>
        </tr>
    </tbody>
</table>
<div>
    <a class="btn btn-primary" role="button" asp-area="" asp-controller="Food" asp-action="List">Back</a>
</div>

DotnetMvc/WebMvc/Views/Food/Edit.cshtml
@model FoodViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Edit Menu";
}

<h2>Edit Menu</h2>
<form asp-action="Update" method="post">
    <div class="form-group">
        <label asp-for="Id">Id</label>
        <input asp-for="Id" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Name">Nama Menu</label>
        <input asp-for="Name" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Category">Jenis</label>
        <input asp-for="Category" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Price">Harga</label>
        <input asp-for="Price" class="form-control">
    </div>
    <div>
        <button type="submit" class="btn btn-primary">Submit</button>
         <a class="btn btn-danger" role="button" asp-area="" asp-controller="Food" asp-action="List">>Back</a>
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DotnetMvc/WebMvc/Views/Food/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Rumah Makan Ampera(n)";
}

<h1>Rumah Makan Ampera(n)</h1>
<p>Merupakan rumah makan pertama yang menggunakan dotnet disini. Rumah makan ini mmemberikan kalian vibes yang kuat.....
    Untuk memesan kalian dapat melihat list makanan atau minuman berk=ikut :
</p>

<div class="align-content-center">
    <a class="btn btn-primary" role="button" asp-area="" asp-controller="Food" asp-action="List">Menu Masakan RM Ampera(n)</a>
</div>

DotnetMvc/WebMvc/Views/Food/List.cshtml
@model List<FoodViewModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "List Menu";
}

<h2>List Menu</h2>
<table class="table table-responsive">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Category</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
    </thead
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Category</td>
                <td>@item.Price</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">
                        <span class="material-icons">
                            edit
                        </span>
                    </a>
                    <a asp-action="Detail" asp-route-id="@item.Id" class="btn btn-sm btn-success">
                        <span class="material-icons">
                            preview 
                        </span>
                    </a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">
                        <span class="material-icons">
                            remove
                        </span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>