DotnetMvc/WebMvc/Models/CarViewModel.cs
namespace WebMvc.Models
{
    public class CarViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public long Price { get; set; }

        public CarViewModel() { }

        public CarViewModel(int id, string name, string type, string brand, long price)
        {
            Id = id;
            Name = name;
            Type = type;
            Brand = brand;
            Price = price;
        }
    }
}

DotnetMvc/WebMvc/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using WebMvc.Models;

namespace WebMvc.Controllers
{
    public class CarController : Controller
    {

        public static List<CarViewModel> carList = new List<CarViewModel>()
        {
            new CarViewModel(1, "Avanza", "Family Car", "Toyota", 65000000),
            new CarViewModel(2, "Xenia", "Family Car", "Daihatsu", 50000000),
            new CarViewModel(3, "GTR R35", "Sport Car", "Nissan", 300000000),
            new CarViewModel(4, "Pathfinder", "Family Car", "Nissan", 100000000),
            new CarViewModel(5, "Supra", "Sport Car", "Toyota", 10000000),
            new CarViewModel(6, "NSX", "Sport Car", "Honda", 1050000)

        };
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {
            return View(carList);
        }


        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Save([Bind("Id, Name, Type, Brand, Price")] CarViewModel car)
        {
            carList.Add(car);
            return Redirect("List");
        }
        public IActionResult Edit(int? id)
        {
            CarViewModel car = carList.Find(x => x.Id.Equals(id));
            return View(car);
        }
        [HttpPost]
        public IActionResult Update(int id, [Bind("Id, Name, Type, Brand, Price")] CarViewModel car)
        {
            CarViewModel carLame = carList.Find(x => x.Id.Equals(id));
            carList.Remove(carLame);
            carList.Add(car);

            return View("List");
        }

        public IActionResult Detail(int id)
        {
            CarViewModel car = (from c in carList where c.Id.Equals(id) select c).SingleOrDefault(new CarViewModel());

            return View(car);
        }
        public IActionResult Delete(int? id)
        {
            CarViewModel car = carList.Find(x => x.Id.Equals(id));
            carList.Remove(car);

            return View("List");
        }



    }

}

DotnetMvc/WebMvc/Views/Car/Add.cshtml
@model CarViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Car Data";
}

<h2>Form Add Car</h2>

<form asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="Id">Id</label>
        <input asp-for="Id" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Type"> Type </label>
        <input asp-for="Type" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Brand">Brand</label>
        <input asp-for="Brand" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Price">Price</label>
        <input asp-for="Price" class="form-control">
    </div

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DotnetMvc/WebMvc/Views/Car/Detail.cshtml
@model CarViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Car Details";
}


<h2>Car Detail</h2>

<table class="table tab-content">
    <tbody>
        <tr>
            <th>ID</th>
            <td>@Model.Id</td>
        </tr>

        <tr>
            <th>Car Name</th>
            <td>@Model.Name</td>
        </tr>

        <tr>
            <th>Type</th>
            <td>@Model.Type</td>
        </tr>

        <tr>
            <th>Brand</th>
            <td>@Model.Brand</td>
        </tr> 
        <tr>
            <th>Price</th>
            <td>@Model.Price</td>
        </tr>
    </tbody>
</table>

<div class="btn">
    <a class="btn btn-primary" role="button" asp-area="" asp-controller="Car" asp-action="List">Back to List of Cars</a>
    <a class="btn btn-primary" role="button" asp-area="" asp-controller="Car" asp-action="Index">Back to Car Mania</a>
</div>

DotnetMvc/WebMvc/Views/Car/Edit.cshtml
@model CarViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Edit Car Data";
}

<h2>Form Edit Cars List</h2>

<form asp-action="Update" method="post">
    <div class="form-group">
        <label asp-for="Id">Id</label>
        <input asp-for="Id" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Name">Car Name</label>
        <input asp-for="Name" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Type">Type</label>
        <input asp-for="Type" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Brand">Brand</label>
        <input asp-for="Brand" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Price">Price</label>
        <input asp-for="Price" class="form-control">
    </div>

    <div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <a class="btn btn-danger" role="button" asp-area="" asp-controller="Car" asp-action="List">Back</a>
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DotnetMvc/WebMvc/Views/Car/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

    ViewData["Title"] = "Car Mania";
}

<h2>Car Mania</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et 
    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu 
    fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<div>
    <a class="btn btn-primary" role="button" asp-area="" asp-controller="Car" asp-action="List">List of Cars</a>
</div>

DotnetMvc/WebMvc/Views/Car/List.cshtml
@model List<CarViewModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Car List";
}

<h2>Car List 2023</h2>

<table class="table table-responsive-md">
     <thead>
        <tr>
            <th>Id</th>
            <th>Cars Name</th>
            <th>Cars Type</th>
            <th>Cars Brand</th>
            <th>Cars PRice</th>
        </tr>
    </thead
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Type</td>
                <td>@item.Brand</td>
                <td>@item.Price</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">
                        <span class="material-icons">
                            edit
                        </span>
                    </a>
                    <a asp-action="Detail" asp-route-id="@item.Id" class="btn btn-sm btn-success">
                        <span class="material-icons">
                            visibility
                        </span>
                    </a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">
                        <span class="material-icons">
                            delete
                        </span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>