DotnetMvc/WebMvc/Models/AbsentViewModel.cs
using System.Xml.Linq;

namespace WebMvc.Models
{
    public class AbsentViewModel
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public DateTime AbsentStartDate { get; set; }
        public DateTime AbsentEndDate { get; set; }
        public String Location { get; set; }
        public String Description { get; set; }

        public AbsentViewModel() { }

       public AbsentViewModel(int id, int employeeId, string name, DateTime absentStartDate, DateTime absentEndDate, string location, string description) : this(id, employeeId, name)
        {
            Id = id;
            EmployeeId = employeeId;
            Name = name;
            AbsentStartDate = absentStartDate;
            AbsentEndDate = absentEndDate;
            Location = location;
            Description = description;
        }

        public AbsentViewModel(int id, int employeeId, string name)
        {
            Id = id;
            EmployeeId = employeeId;
            Name = name;

        }
    }
}

DotnetMvc/WebMvc/Controllers/AbsentController.cs
using Microsoft.AspNetCore.Mvc;
using WebMvc.Models;

namespace WebMvc.Controllers
{
    public class AbsentController : Controller
    {
        public static List<AbsentViewModel> absentList = new List<AbsentViewModel>()
        {
            new AbsentViewModel(1, 123, "Shidqi"),
            new AbsentViewModel(2, 223, "Rama"),
            new AbsentViewModel(3, 123, "Rizqi")
        };
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult List()
        {
            return View(absentList);
        }

        [HttpPost]
        public IActionResult Save([Bind("EmployeeId, Name, AbsentStartDate, AbsentEndDate, Location, Description")] AbsentViewModel absent)
        {
            absentList.Add(absent);
            return Redirect("Index");
        }

        public IActionResult Out(int? id)
        {
            AbsentViewModel absent = absentList.Find(x => x.Id.Equals(id));
            return View(absent);
           
        }

        [HttpPost]
        public IActionResult Update(int id, [Bind ("EmployeeId, Name, AbsentStartDate, AbsentEndDate, Location, Description")] AbsentViewModel absent)
        {
            AbsentViewModel absentOld = absentList.Find(x => x.Id.Equals(id));
            absentList.Remove(absentOld);
            absentList.Add(absent);

            return View("List");
        }


    }
}

DotnetMvc/WebMvc/Views/Absent/Index.cshtml
@model AbsentViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Absensi Masuk";
}

<h2>Form Absensi Masuk</h2>

<form asp-action="Save" method="post">
    
    <div class="form-group">
        <label asp-for="EmployeeId">Id Karyawan</label>
        <input asp-for="EmployeeId" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Name">Nama</label>
        <input asp-for="Name" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="AbsentStartDate" class="control-label">Absen Masuk</label>
        <div class='input-group date' id='datetimepicker1'>
            <input asp-for="AbsentStartDate" class="form-control" />
                     <span class="input-group-addon">
                     <span class="glyphicon glyphicon-calendar"></span>
                     </span>
    </div>
    </div>
    <div class="form-group">
        <label asp-for="Location">Lokasi</label>
        <input asp-for="Location" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Description">Keterangan</label>
        <input asp-for="Description" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<script>
     $(function () {
       $('#datetimepicker1').datetimepicker();
    });
</script>

DotnetMvc/WebMvc/Views/Absent/List.cshtml
@model List<AbsentViewModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "List Absensi";
}

<h2>List Absensi</h2>
<table class="table table-responsive">
    <thead>
        <tr>
            <th>Id Karyawan</th>
            <th>Nama</th>
            <th>Absen Masuk</th>
            <th>Absen Keluar</th>
            <th>Lokasi</th>
            <th>Keterangan</th>
            <th>Absen Keluar</th>
        </tr>
    </thead
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.EmployeeId</td>
                <td>@item.Name</td>
                <td>@item.AbsentStartDate</td>
                <td>@item.AbsentEndDate</td>
                <td>@item.Location</td>
                <td>@item.Description</td>
                <td>
                    <a asp-action="Out" asp-route-id="@item.Id" class="btn btn-sm btn-warning">
                        <span class="material-icons">
                            edit
                        </span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a class="btn btn-primary" role="button" asp-area="" asp-controller="Absent" asp-action="Index">Absen Masuk</a>

</div>

DotnetMvc/WebMvc/Views/Absent/Out.cshtml
@model AbsentViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Absensi Keluar";
}

<h2>Form Absensi Keluar</h2>

<form asp-action="Update" method="post">
    <div class="form-group">
        <label asp-for="Name">Nama</label>
        <input asp-for="Name" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="AbsentStartDate" class="control-label">Absen Masuk</label>
        <div class='input-group date' id='datetimepicker1'>
            <input asp-for="AbsentStartDate" class="form-control" readonly />
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="AbsentEndDate" class="control-label">Absen Keluar</label>
        <div class='input-group date' id='datetimepicker1'>
            <input asp-for="AbsentEndDate" class="form-control" />
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<script>
    $(function () {
        $('#datetimepicker1').datetimepicker();
    });
</script>